### ISSUE TITLE
PRTG nodes not appearing in Node-Red

### ISSUE THREAD

**Issue by ShiftMakaveli** [PaesslerAG/node-red-contrib-prtg#17]
Hello!
I've installed the PRTG nodes for Node-Red to connect it with my PRTG instance. After several tries of installation the PRTG nodes are still not showing up in the Dashboard. In the Palette Manager it says that "paesslerag-node-red-contrib-prtg" is installed and that two nodes (prtg-config and prtg-connector) are existing but they are colored grey. Also I tried to update the installation in the Dashboard so it is updated to Version 1.0.1 but still it isn't showing up as a node.

OS: Windows 10
Used Version of Node-Red: v1.1.2
Used Version of Node.js: v12.18.2
Microsoft Edge 44.18362.449.0

![image](https://user-images.githubusercontent.com/68636805/88152519-6edaf400-cc04-11ea-823e-115e615cc0f1.png)

**Comment by Newan** [comment]
Please test Chrome or Firefox.

**Comment by mhengl** [comment]
Hi @ShiftMakaveli, maybe this is something most easily solved by a short remote session. If you have some time join https://discord.gg/bqmQtEY and ping me.

**Comment by ShiftMakaveli** [comment]
Hello,
after I've updated Microsoft Edge to the latest version, the prtg-connector node suddenly appeared in the dashboard.
Thank you very much!
